<?php

if ( ! defined( 'ABSPATH' ) ) {
  exit;
}

return array(
        'Abingdon',
        'Accrington',
        'Acton',
        'Adlington',
        'Alcester',
        'Aldeburgh',
        'Aldershot',
        'Aldridge',
        'Alford',
        'Alfreton',
        'Alnwick',
        'Alsager',
        'Alston',
        'Alton',
        'Altrincham',
        'Amble',
        'Amersham',
        'Amesbury',
        'Ampthill',
        'Andover',
        'Appleby-in-Westmorland',
        'Arundel',
        'Ashbourne',
        'Ashburton',
        'Ashby-de-la-Zouch',
        'Ashford',
        'Ashington',
        'Ashton-in-Makerfield',
        'Ashton-under-Lyne',
        'Askern',
        'Aspatria',
        'Atherstone',
        'Attleborough',
        'Axbridge',
        'Axminster',
        'Aylesbury',
        'Aylsham',
        'Bacup',
        'Bakewell',
        'Baldock',
        'Banbury',
        'Barking',
        'Barnard Castle',
        'Barnet',
        'Barnoldswick',
        'Barnsley',
        'Barnstaple',
        'Barnt Green',
        'Barrow-in-Furness',
        'Barton-upon-Humber',
        'Basildon',
        'Basingstoke',
        'Bath',
        'Batley',
        'Battle',
        'Bawtry',
        'Beaconsfield',
        'Beaminster',
        'Bebington',
        'Beccles',
        'Bedale',
        'Bedford',
        'Bedlington',
        'Bedworth',
        'Beeston',
        'Belper',
        'Bentham',
        'Berkhamsted',
        'Berwick-upon-Tweed',
        'Beverley',
        'Bewdley',
        'Bexhill-on-Sea',
        'Bicester',
        'Biddulph',
        'Bideford',
        'Biggleswade',
        'Billericay',
        'Bilston',
        'Bingham',
        'Birmingham',
        'Bishop Auckland',
        'Bishop\' Castle',
        'Bishop\' Stortford',
        'Bishop\' Waltham',
        'Blackburn',
        'Blackpool',
        'Blandford Forum',
        'Bletchley',
        'Blyth',
        'Bodmin',
        'Bognor Regis',
        'Bollington',
        'Bolsover',
        'Bolton',
        'Borehamwood',
        'Boston',
        'Bottesford',
        'Bourne',
        'Bournemouth',
        'Brackley',
        'Bracknell',
        'Bradford',
        'Bradford-on-Avon',
        'Bradley Stoke',
        'Bradninch',
        'Braintree',
        'Brentford',
        'Brentwood',
        'Bridgnorth',
        'Bridgwater',
        'Bridlington',
        'Bridport',
        'Brierley Hill',
        'Brigg',
        'Brighouse',
        'Brightlingsea',
        'Brighton',
        'Bristol',
        'Brixham',
        'Broadstairs',
        'Bromley',
        'Bromsgrove',
        'Bromyard',
        'Brownhills',
        'Buckfastleigh',
        'Buckingham',
        'Bude',
        'Budleigh Salterton',
        'Bungay',
        'Buntingford',
        'Burford',
        'Burgess Hill',
        'Burnham-on-Crouch',
        'Burnham-on-Sea',
        'Burnley',
        'Burntwood',
        'Burton Latimer',
        'Burton-upon-Trent',
        'Bury',
        'Bury St Edmunds',
        'Buxton',
        'Caistor',
        'Calne',
        'Camberley',
        'Camborne',
        'Cambridge',
        'Camelford',
        'Cannock',
        'Canterbury',
        'Carlisle',
        'Carnforth',
        'Carterton',
        'Castle Cary',
        'Castleford',
        'Chadderton',
        'Chagford',
        'Chard',
        'Charlbury',
        'Chatham',
        'Chatteris',
        'Chelmsford',
        'Cheltenham',
        'Chesham',
        'Cheshunt',
        'Chester',
        'Chesterfield',
        'Chester-le-Street',
        'Chichester',
        'Chippenham',
        'Chipping Campden',
        'Chipping Norton',
        'Chipping Ongar',
        'Chipping Sodbury',
        'Chorley',
        'Christchurch',
        'Church Stretton',
        'Cinderford',
        'Cirencester',
        'Clacton-on-Sea',
        'Cleckheaton',
        'Cleethorpes',
        'Clevedon',
        'Clitheroe',
        'Clun',
        'Coalville',
        'Cockermouth',
        'Coggeshall',
        'Colchester',
        'Coleford',
        'Colne',
        'Congleton',
        'Conisbrough',
        'Corbridge',
        'Corby',
        'Cotgrave',
        'Coventry',
        'Cowes',
        'Cramlington',
        'Crawley',
        'Crayford',
        'Crediton',
        'Crewe',
        'Crewkerne',
        'Cromer',
        'Crowborough',
        'Crowle',
        'Crowthorne',
        'Croydon',
        'Cuckfield',
        'Cullompton',
        'Dagenham',
        'Darley Dale',
        'Darlington',
        'Dartford',
        'Dartmouth',
        'Darwen',
        'Daventry',
        'Dawlish',
        'Deal',
        'Denton',
        'Derby',
        'Dereham',
        'Desborough',
        'Devizes',
        'Dewsbury',
        'Didcot',
        'Dinnington',
        'Diss',
        'Doncaster',
        'Dorchester',
        'Dorking',
        'Dover',
        'Downham Market',
        'Driffield',
        'Dronfield',
        'Droitwich Spa',
        'Droylsden',
        'Dudley',
        'Dukinfield',
        'Dunstable',
        'Durham',
        'Dursley',
        'Ealing',
        'Earley',
        'Easingwold',
        'Eastbourne',
        'East Grinstead',
        'East Ham',
        'Eastleigh',
        'Eastwood',
        'Edenbridge',
        'Egham',
        'Ellesmere',
        'Ellesmere Port',
        'Ely',
        'Enfield',
        'Epping',
        'Epsom',
        'Epworth',
        'Erith',
        'Esher',
        'Eton',
        'Evesham',
        'Exeter',
        'Exmouth',
        'Eye',
        'Failsworth',
        'Fairford',
        'Fakenham',
        'Falmouth',
        'Fareham',
        'Faringdon',
        'Farnborough',
        'Farnham',
        'Farnworth',
        'Faversham',
        'Featherstone',
        'Felixstowe',
        'Fenny Stratford',
        'Ferndown',
        'Ferryhill',
        'Filey',
        'Filton',
        'Fleet',
        'Fleetwood',
        'Flitwick',
        'Folkestone',
        'Fordingbridge',
        'Fordwich',
        'Fowey',
        'Framlingham',
        'Frinton-on-Sea',
        'Frodsham',
        'Frome',
        'Gainsborough',
        'Gateshead',
        'Gillingham',
        'Gillingham',
        'Glastonbury',
        'Glossop',
        'Gloucester',
        'Godalming',
        'Godmanchester',
        'Goole',
        'Gosport',
        'Grange-over-Sands',
        'Grantham',
        'Gravesend',
        'Grays',
        'Great Dunmow',
        'Great Torrington',
        'Great Yarmouth',
        'Grimsby',
        'Guildford',
        'Guisborough',
        'Hackney',
        'Hadleigh',
        'Hailsham',
        'Halesworth',
        'Halewood',
        'Halifax',
        'Halstead',
        'Haltwhistle',
        'Harlow',
        'Harpenden',
        'Harrogate',
        'Harrow',
        'Hartlepool',
        'Harwich',
        'Haslemere',
        'Hastings',
        'Hatfield',
        'Havant',
        'Haverhill',
        'Hawley',
        'Hayle',
        'Haywards Heath',
        'Heanor',
        'Heathfield',
        'Hebden Bridge',
        'Hedon',
        'Helston',
        'Hemel Hempstead',
        'Hemsworth',
        'Henley-in-Arden',
        'Henley-on-Thames',
        'Hendon',
        'Hereford',
        'Herne Bay',
        'Hertford',
        'Hessle',
        'Heswall',
        'Hetton-le-Hole',
        'Heywood',
        'Hexham',
        'Higham Ferrers',
        'Highworth',
        'High Wycombe',
        'Hinckley',
        'Hitchin',
        'Hoddesdon',
        'Holmfirth',
        'Holsworthy',
        'Honiton',
        'Horley',
        'Horncastle',
        'Hornsea',
        'Horsham',
        'Horwich',
        'Houghton-le-Spring',
        'Hounslow',
        'Hoylake',
        'Hove Hucknall',
        'Huddersfield',
        'Hugh Town',
        'Hungerford',
        'Hunstanton',
        'Huntingdon',
        'Hyde',
        'Hythe',
        'Ilchester',
        'Ilford',
        'Ilfracombe',
        'Ilkeston',
        'Ilkley',
        'Ilminster',
        'Ipswich',
        'Irthlingborough',
        'Ivybridge',
        'Jarrow',
        'Keighley',
        'Kempston',
        'Kendal',
        'Kenilworth',
        'Kesgrave',
        'Keswick',
        'Kettering',
        'Keynsham',
        'Kidderminster',
        'Kidsgrove',
        'Killingworth',
        'Kimberley',
        'Kingsbridge',
        'King\' Lynn',
        'Kingston-upon-Hull',
        'Kingston upon Thames',
        'Kington',
        'Kirkby',
        'Kirkby Lonsdale',
        'Kirkham',
        'Knaresborough',
        'Knottingley',
        'Knutsford',
        'Lancaster',
        'Launceston',
        'Leatherhead',
        'Leamington Spa',
        'Lechlade',
        'Ledbury',
        'Leeds',
        'Leek',
        'Leicester',
        'Leighton Buzzard',
        'Leiston',
        'Leominster',
        'Letchworth',
        'Lewes',
        'Lewisham',
        'Leyland',
        'Leyton',
        'Lichfield',
        'Lincoln',
        'Liskeard',
        'Littlehampton',
        'Liverpool',
        'Lizard',
        'London',
        'Long Eaton',
        'Longridge',
        'Looe',
        'Lostwithiel',
        'Loughborough',
        'Loughton',
        'Louth',
        'Lowestoft',
        'Ludlow',
        'Luton',
        'Lutterworth',
        'Lydd',
        'Lydney',
        'Lyme Regis',
        'Lymington',
        'Lynton',
        'Lytchett Minster',
        'Lytham St Annes',
        'Mablethorpe',
        'Macclesfield',
        'Maghull',
        'Maidenhead',
        'Maidstone',
        'Maldon',
        'Malmesbury',
        'Maltby',
        'Malton',
        'Malvern',
        'Manchester',
        'Manningtree',
        'Mansfield',
        'March',
        'Margate',
        'Market Deeping',
        'Market Drayton',
        'Market Harborough',
        'Market Rasen',
        'Market Weighton',
        'Marlborough',
        'Marlow',
        'Maryport',
        'Matlock',
        'Melksham',
        'Melton Mowbray',
        'Mexborough',
        'Middleham',
        'Middlesbrough',
        'Middleton',
        'Middlewich',
        'Midhurst',
        'Midsomer Norton',
        'Milton Keynes',
        'Minehead',
        'Morecambe',
        'Moretonhampstead',
        'Moreton-in-Marsh',
        'Morley',
        'Morpeth',
        'Much Wenlock',
        'Nailsea',
        'Nailsworth',
        'Nantwich',
        'Needham Market',
        'Neston',
        'Newark-on-Trent',
        'Newbiggin-by-the-Sea',
        'Newbury',
        'Newcastle-under-Lyme',
        'Newcastle upon Tyne',
        'Newent',
        'Newhaven',
        'Newmarket',
        'New Mills',
        'New Milton',
        'Newport',
        'Newport',
        'Shropshire',
        'Newport Pagnell',
        'Newquay',
        'New Romney',
        'Newton Abbot',
        'Newton Aycliffe',
        'Newton-le-Willows',
        'Normanton',
        'Northallerton',
        'Northam',
        'Northampton',
        'North Walsham',
        'Northwich',
        'Norton Radstock',
        'Norwich',
        'Nottingham',
        'Nuneaton',
        'Oakham',
        'Okehampton',
        'Oldbury',
        'Oldham',
        'Ollerton',
        'Olney',
        'Ormskirk',
        'Orpington',
        'Ossett',
        'Oswestry',
        'Otley',
        'Ottery St Mary',
        'Oundle',
        'Oxford',
        'Paddock Wood',
        'Padstow',
        'Paignton',
        'Painswick',
        'Peacehaven',
        'Penistone',
        'Penrith',
        'Penryn',
        'Penzance',
        'Pershore',
        'Peterborough',
        'Peterlee',
        'Petersfield',
        'Petworth',
        'Pickering',
        'Plymouth',
        'Pocklington',
        'Pontefract',
        'Polegate',
        'Poltimore',
        'Poole',
        'Portishead',
        'Portland',
        'Portslade',
        'Portsmouth',
        'Potters Bar',
        'Potton',
        'Poulton-le-Fylde',
        'Prescot',
        'Preston',
        'Princes Risborough',
        'Prudhoe',
        'Pudsey',
        'Queenborough',
        'Ramsgate',
        'Raunds',
        'Rayleigh',
        'Reading',
        'Redcar',
        'Redditch',
        'Redhill',
        'Redruth',
        'Reigate',
        'Retford',
        'Richmond',
        'Richmond-upon-Thames',
        'Rickmansworth',
        'Ringwood',
        'Ripley',
        'Ripon',
        'Rochdale',
        'Rochester',
        'Rochford',
        'Romford',
        'Romsey',
        'Ross-on-Wye',
        'Rothbury',
        'Rotherham',
        'Rothwell',
        'Rowley Regis',
        'Royston',
        'Rugby',
        'Rugeley',
        'Runcorn',
        'Rushden',
        'Ryde',
        'Rye',
        'Saffron Walden',
        'St Albans',
        'St Austell',
        'St Blazey',
        'St Columb Major',
        'St Helens',
        'St Ives',
        'Cambridgeshire',
        'St Ives',
        'Cornwall',
        'St Neots',
        'Salcombe',
        'Sale',
        'Salford',
        'Salisbury',
        'Saltash',
        'Saltburn-by-the-Sea',
        'Sandbach',
        'Sandhurst',
        'Sandown',
        'Sandwich',
        'Sandy',
        'Sawbridgeworth',
        'Saxmundham',
        'Scarborough',
        'Scunthorpe',
        'Seaford',
        'Seaton',
        'Sedgefield',
        'Selby',
        'Selsey',
        'Settle',
        'Sevenoaks',
        'Shaftesbury',
        'Shanklin',
        'Sheerness',
        'Sheffield',
        'Shepshed',
        'Shepton Mallet',
        'Sherborne',
        'Sheringham',
        'Shildon',
        'Shipston-on-Stour',
        'Shoreham-by-Sea',
        'Shrewsbury',
        'Sidmouth',
        'Sittingbourne',
        'Skegness',
        'Skelmersdale',
        'Skipton',
        'Sleaford',
        'Slough',
        'Smethwick',
        'Snodland',
        'Soham',
        'Solihull',
        'Somerton',
        'Southall',
        'Southam',
        'Southampton',
        'Southborough',
        'Southend-on-Sea',
        'South Molton',
        'Southport',
        'Southsea',
        'South Shields',
        'Southwell',
        'Southwold',
        'South Woodham Ferrers',
        'Spalding',
        'Spennymoor',
        'Spilsby',
        'Stafford',
        'Staines',
        'Stainforth',
        'Stalybridge',
        'Stamford',
        'Stanley',
        'Stapleford',
        'Staunton',
        'Staveley',
        'Stevenage',
        'Stockport',
        'Stocksbridge',
        'Stockton-on-Tees',
        'Stoke-on-Trent',
        'Stone',
        'Stony Stratford',
        'Stotfield',
        'Stourbridge',
        'Stourport-on-Severn',
        'Stowmarket',
        'Stow-on-the-Wold',
        'Stratford-upon-Avon',
        'Streatham',
        'Strood',
        'Stroud',
        'Sudbury',
        'Sunderland',
        'Sutton',
        'Sutton Coldfield',
        'Sutton-in-Ashfield',
        'Swadlincote',
        'Swaffham',
        'Swanage',
        'Swanley',
        'Swindon',
        'Swinton',
        'Tadcaster',
        'Tadley',
        'Tamworth',
        'Taunton',
        'Tavistock',
        'Teignmouth',
        'Telford',
        'Tenbury Wells',
        'Tenterden',
        'Tetbury',
        'Tewkesbury',
        'Thame',
        'Thatcham',
        'Thaxted',
        'Thetford',
        'Thirsk',
        'Thong',
        'Thornaby',
        'Thornbury',
        'Thorne',
        'Tickhill',
        'Tilbury',
        'Tipton',
        'Tiverton',
        'Todmorden',
        'Tonbridge',
        'Torpoint',
        'Torquay',
        'Totnes',
        'Tottenham',
        'Totton',
        'Towcester',
        'Tring',
        'Trowbridge',
        'Truro',
        'Tunbridge Wells',
        'Twickenham',
        'Uckfield',
        'Ulverston',
        'Uppingham',
        'Upton-upon-Severn',
        'Uttoxeter',
        'Uxbridge',
        'Ventnor',
        'Verwood',
        'Wadebridge',
        'Wadhurst',
        'Wakefield',
        'Wallasey',
        'Wallingford',
        'Walmer',
        'Walsall',
        'Waltham Abbey',
        'Waltham Cross',
        'Walthamstow',
        'Walton-on-Thames',
        'Walton-on-the-Naze',
        'Wandsworth',
        'Wantage',
        'Ware',
        'Wareham',
        'Warminster',
        'Warrington',
        'Warwick',
        'Washington',
        'Watchet',
        'Watford',
        'Wath-upon-Dearne',
        'Watton',
        'Wednesbury',
        'Wellingborough',
        'Wellington',
        'Wells',
        'Wells-next-the-Sea',
        'Welwyn Garden City',
        'Wem',
        'Wendover',
        'West Bromwich',
        'Westbury',
        'Westerham',
        'West Ham',
        'Westhoughton',
        'West Kirby',
        'West Mersea',
        'Westminster',
        'Weston-super-Mare',
        'Westward Ho!',
        'Wetherby',
        'Weybridge',
        'Weymouth',
        'Whaley Bridge',
        'Whiston',
        'Whitby',
        'Whitchurch',
        'Whitehaven',
        'Whitley Bay',
        'Whitnash',
        'Whitstable',
        'Whitworth',
        'Wickford',
        'Widnes',
        'Wigan',
        'Wigston',
        'Willenhall',
        'Wimbledon',
        'Wimborne Minster',
        'Wincanton',
        'Winchcombe',
        'Winchelsea',
        'Winchester',
        'Windermere',
        'Winsford',
        'Winslow',
        'Wisbech',
        'Witham',
        'Withernsea',
        'Witney',
        'Wivenhoe',
        'Woburn',
        'Woking',
        'Wokingham',
        'Wolverhampton',
        'Wombwell',
        'Woodbridge',
        'Woodstock',
        'Wooler',
        'Woolwich',
        'Wootton Bassett',
        'Worcester',
        'Workington',
        'Worksop',
        'Worthing',
        'Wotton-under-Edge',
        'Wycombe',
        'Wymondham',   
    
        'Acton',
        'Aghacommon',
        'Aghadowey',
        'Aghadrumsee',
        'Aghagallon',
        'Aghalee',
        'Ahoghill',
        'Aldergrove',
        'Altamuskin',
        'Altishane',
        'Altmore',
        'Annaclone',
        'Annaghmore',
        'Annahilt',
        'Annahugh',
        'Annalong',
        'Annsborough',
        'Antrim',
        'Ardboe',
        'Ardgarvan',
        'Ardglass',
        'Ardmore',
        'Ardstraw',
        'Armagh',
        'Armoy',
        'Arney',
        'Articlave',
        'Artigarvan',
        'Artikelly',
        'Atticall',
        'Aughafatten',
        'Augher',
        'Aughnacloy',
        'Ballela',
        'Ballerin',
        'Ballinamallard',
        'Ballintoy',
        'Balloo',
        'Ballybogy',
        'Ballycarry',
        'Ballycassidy',
        'Ballycastle',
        'Ballyclare',
        'Ballyeaston',
        'Ballygalley',
        'Ballygawley',
        'Ballygowan',
        'Ballyhalbert',
        'Ballyhornan',
        'Ballykelly',
        'Ballykinler',
        'Ballylesson',
        'Ballylinney',
        'Ballymacmaine',
        'Ballymacnab',
        'Ballymagorry',
        'Ballymartin',
        'Ballymaguigan',
        'Ballymena',
        'Ballymoney',
        'Ballynahinch',
        'Ballynure',
        'Ballyrashane',
        'Ballyrobert',
        'Ballyronan',
        'Ballyrory',
        'Ballyscullion',
        'Ballyskeagh',
        'Ballystrudder',
        'Ballyvoy',
        'Ballywalter',
        'Balnamore',
        'Banagher',
        'Banbridge',
        'Bangor',
        'Bannfoot',
        'Belcoo',
        'Bellaghy',
        'Bellanaleck',
        'Bellarena',
        'Belleek',
        'Belleeks',
        'Benburb',
        'Bendooragh',
        'Beragh',
        'Bessbrook',
        'Blackskull',
        'Blackwatertown',
        'Blaney',
        'Bleary',
        'Boho',
        'Brackaville',
        'Bready',
        'Brockagh',
        'Brookeborough',
        'Broomhill',
        'Broughshane',
        'Bryansford',
        'Buckna',
        'Burnfoot',
        'Burren',
        'Bushmills',
        'Caledon',
        'Camlough',
        'Campsey',
        'Capecastle',
        'Cappagh',
        'Cargan',
        'Carnalbanagh',
        'Carncastle',
        'Carnlough',
        'Carnteel',
        'Carrickaness',
        'Carrickfergus',
        'Carrickmore',
        'Carrowclare',
        'Carrowdore',
        'Carrybridge',
        'Carryduff',
        'Castlecaulfield',
        'Castledawson',
        'Castlederg',
        'Castlerock',
        'Castlewellan',
        'Charlemont',
        'Clabby',
        'Clady (Co. Londonderry)',
        'Clady (Co. Tyrone)',
        'Cladymore',
        'Clanabogan',
        'Claudy',
        'Clogh',
        'Clogher',
        'Cloghy',
        'Clonmore',
        'Clonoe',
        'Clough',
        'Cloughmills',
        'Coagh',
        'Coalisland',
        'Cogry-Kilbride',
        'Coleraine',
        'Collegeland',
        'Comber',
        '(convoy) Conlig',
        'Cookstown',
        'Corbet',
        'Corrinshego',
        'Craigarogan',
        'Craigavon',
        'Cranagh',
        'Crawfordsburn',
        'Creagh',
        'Creggan',
        'Crossgar',
        'Crossmaglen',
        'Crumlin',
        'Cullaville',
        'Cullybackey',
        'Cullyhanna',
        'Culmore',
        'Culnady',
        'Curran',
        'Cushendall',
        'Cushendun',
        'Darkley',
        'Derryadd',
        'Derrycrin',
        'Derrygonnelly',
        'Derryhale',
        'Derrylin',
        'Derrymacash',
        'Derrymore',
        'Derrynaflaw',
        'Derrynoose',
        'Derrytrasna',
        'Derryvore',
        'Dervock',
        'Desertmartin',
        'Doagh',
        'Dollingstown',
        'Donagh',
        'Donaghadee',
        'Donaghcloney',
        'Donaghey',
        'Donaghmore',
        'Donegore',
        'Dooish',
        'Dorsy',
        'Douglas Bridge',
        'Downhill',
        'Downpatrick',
        'Draperstown',
        'Drinns Bay',
        'Dromara',
        'Dromore (Co. Down)',
        'Dromore (Co. Tyrone)',
        'Drumaness',
        'Drumbeg',
        'Drumbo',
        'Drumintee',
        'Drumlaghy',
        'Drumlough',
        'Drumlough',
        'Drummullan',
        'Drumnacanvy',
        'Drumnakilly',
        'Drumquin',
        'Drumraighland',
        'Drumsurn',
        'Dunadry',
        'Dundonald',
        'Dundrod',
        'Dundrum',
        'Dungannon',
        'Dungiven',
        'Dunloy',
        'Dunnamanagh',
        'Dunnamore',
        'Dunnaval',
        'Dunseverick',
        'Edenaveys',
        'Edenderry',
        'Ederney',
        'Eglinton',
        'Eglish',
        'Enniskillen',
        'Erganagh',
        'Eskra',
        'Feeny',
        'Fintona',
        'Fivemiletown',
        'Florencecourt',
        'Foreglen',
        'Forkill',
        'Galbally',
        'Gamblestown',
        'Garrison',
        'Garvagh',
        'Garvaghey',
        'Garvetagh',
        'Gawley\'s Gate',
        'Gibson\'s Hill',
        'Gilford',
        'Gillygooly',
        'Glack',
        'Glebe',
        'Glenarm',
        'Glenavy',
        'Glenmornan',
        'Glenoe',
        'Glenone',
        'Glynn',
        'Gortaclare',
        'Gortin',
        'Gortnahey',
        'Goshedan',
        'Gracehill',
        'Grange Corner',
        'Granville',
        'Greencastle',
        'Greenisland',
        'Greyabbey',
        'Greysteel',
        'Groggan',
        'Groomsport',
        'Gulladuff',
        'Halfpenny Gate',
        'Hamiltonsbawn',
        'Helen\'s Bay',
        'Hillhall',
        'Hillsborough',
        'Hilltown',
        'Holywell',
        'Holywood',
        'Inishrush',
        'Irvinestown',
        'Jonesborough',
        'Katesbridge',
        'Keady',
        'Kells-Connor',
        'Kellswater',
        'Kesh',
        'Keshbridge',
        'Kilcoo',
        'Kildress',
        'Kilkeel',
        'Killadeas',
        'Killaloo',
        'Killay',
        'Killead',
        'Killeen',
        'Killen',
        'Killeter',
        'Killinchy',
        'Killough',
        'Killowen',
        'Killylea',
        'Killyleagh',
        'Killyman',
        'Killywool',
        'Kilmore',
        'Kilrea',
        'Kilskeery',
        'Kinallen',
        'Kinawley',
        'Kircubbin',
        'Knockcloghrim',
        'Knockmoyle',
        'Knocknacarry',
        'Lack',
        'Landahaussy',
        'Largy',
        'Larne',
        'Lawrencetown',
        'Letterbreen',
        'Lettershendoney',
        'Limavady',
        'Lisbellaw',
        'Lisburn',
        'Lislea',
        'Lisnadill',
        'Lisnarick',
        'Lisnaskea',
        'Loughbrickland',
        'Loughgall',
        'Loughgilly',
        'Loughguile',
        'Loughinisland',
        'Loughmacrory',
        'Loup',
        'Lower Ballinderry',
        'Lurgan',
        'Lurganare',
        'Lurganure',
        'Lurganville',
        'Macken',
        'Macosquin',
        'Madden',
        'Maghaberry',
        'Maghera',
        'Magheraconluce',
        'Magherafelt',
        'Magheralin',
        'Magheramason',
        'Magheramorne',
        'Magheraveely',
        'Maghery',
        'Maguiresbridge',
        'Markethill',
        'Martinstown',
        'Maydown',
        'Mayobridge',
        'Mazetown',
        'Meigh',
        'Middletown',
        'Milford',
        'Millbank',
        'Mill Bay',
        'Millisle',
        'Milltown',
        'Moira',
        'Monea',
        'Moneyglass',
        'Moneymore',
        'Moneyneany',
        'Moneyreagh',
        'Moneyslane',
        'Monteith',
        'Moortown',
        'Moss-Side',
        'Mountfield',
        'Mountjoy',
        'Mounthill',
        'Mountnorris',
        'Moy',
        'Moygashel',
        'Mullaghbawn',
        'Mullaghboy',
        'Mullaghbrack',
        'Mullaghglass',
        'Mullavilly-Laurelvale',
        'Newbuildings',
        'Newcastle',
        'Newry',
        'Newtown Crommelin',
        'Newtownabbey',
        'Newtownards',
        'Newtownbutler',
        'Newtowncloghoge',
        'Newtownhamilton',
        'Newtownstewart',
        'Nixon\'s Corner',
        'Newmills',
        'Omagh',
        'Park',
        'Parkgate',
        'Plumbridge',
        'Pomeroy',
        'Portadown',
        'Portaferry',
        'Portavogie',
        'Portballintrae',
        'Portbraddon',
        'Portglenone',
        'Portrush',
        'Portstewart',
        'Poyntzpass',
        'Randalstown',
        'Rasharkin',
        'Rathfriland',
        'Ravernet',
        'Richhill',
        'Ringsend',
        'Rock',
        'Rosslea',
        'Rostrevor',
        'Roughfort',
        'Rousky',
        'Saintfield',
        'Sandholes',
        'Scarva',
        'Scotch Street',
        'Seaforde',
        'Seskinore',
        'Shanmaghery',
        'Shanvey',
        'Sheeptown',
        'Shrigley',
        'Silverbridge',
        'Sion Mills',
        'Sixmilecross',
        'Skea',
        'Spa',
        'Spamount',
        'Springfield',
        'Stewartstown',
        'Stoneyford',
        'Strabane',
        'Straid',
        'Straidarran',
        'Strangford',
        'Stranocum',
        'Strathfoyle',
        'Straw',
        'Swatragh',
        'Tamnamore',
        'Tandragee',
        'Tartaraghan',
        'Teemore',
        'Templepatrick',
        'Tempo',
        'The Birches',
        'Tobermore',
        'Toome',
        'Trillick',
        'Trory',
        'Tullyhogue',
        'Tullyhommon',
        'Tullylish',
        'Tullynacross',
        'Tullywiggan',
        'Tynan',
        'Upper Ballinderry',
        'Upperlands',
        'Victoria Bridge',
        'Waringsford',
        'Waringstown',
        'Warrenpoint',
        'Washing Bay',
        'Waterfoot',
        'Whitecross',
        'Whitehead',
        'Whiterock',
        'Aberdeen',
        'Airdrie',
        'Alloa',
        'Arbroath',
        'Ayr',
        'Barrhead',
        'Bathgate',
        'Bearsden',
        'Bellshill',
        'Bishopbriggs',
        'Blantyre',
        'Buckhaven',
        'Cambuslang',
        'Clarkston',
        'Clydebank',
        'Coatbridge',
        'Cumbernauld',
        'Dumbarton',
        'Dumfries',
        'Dundee',
        'Dunfermline',
        'East Kilbride',
        'Edinburgh',
        'Elgin',
        'Erskine',
        'Falkirk',
        'Giffnock',
        'Glenrothes',
        'Grangemouth',
        'Greenock',
        'Hamilton',
        'Inverness',
        'Irvine',
        'Johnstone',
        'Kilmarnock',
        'Kilwinning',
        'Kirkcaldy',
        'Kirkintilloch',
        'Larkhall',
        'Livingston',
        'Motherwell',
        'Musselburgh',
        'Newton Mearns',
        'Paisley',
        'Penicuik',
        'Perth',
        'Peterhead',
        'Polmont',
        'Renfrew',
        'Rutherglen',
        'St Andrews',
        'Stenhousemuir',
        'Stirling',
        'Viewpark',
        'Wishaw',
        'Cardiff',
        'Aberaeron',
        'Abercanaid',
        'Abercarn',
        'Newbridge',
        'Aberdare',
        'Abergavenny',
        'Abergele',
        'Aberkenfig',
        'Bryncoch',
        'Aberporth',
        'Abertillery',
        'Abertridwr',
        'Senghenydd',
        'Aberystwyth',
        'Amlwch',
        'Ammanford',
        'Bagillt',
        'Bala',
        'Bangor',
        'Bargoed',
        'Barmouth',
        'Barry',
        'Beaumaris',
        'Beddau',
        'Bedwas',
        'Benllech',
        'Bethesda',
        'Betws',
        'Bishopston',
        'Blackwood',
        'Blaenau Ffestiniog',
        'Blaenavon',
        'Bodelwyddan',
        'Bow Street',
        'Brecon',
        'Bridgend',
        'Brymbo',
        'Gwersyllt',
        'Brynaman',
        'Gwaun-Cae-Gurwen',
        'Brynmawr',
        'Buckley',
        'Builth Wells',
        'Burry Port',
        'Caerleon',
        'Caernarfon',
        'Caerphilly',
        'Caldicot',
        'Cardigan',
        'Carmarthen',
        'Cefn-mawr',
        'Chepstow',
        'Chirk',
        'Church Village',
        'Coedpoeth',
        'Colwyn Bay',
        'Connah\'s Quay',
        'Conwy',
        'Cowbridge',
        'Creigiau',
        'Criccieth',
        'Croeserw',
        'Cross Hands',
        'Crynant',
        'Cwm',
        'Cwmafan',
        'Pontrhydyfen',
        'Cwmbach',
        'Cwmbran',
        'Cwmllynfell',
        'Cyfarthfa',
        'Denbigh',
        'Dinas Powys',
        'Dolgellau',
        'Dyserth',
        'Ebbw Vale',
        'Ferndale',
        'Fishguard',
        'Flint',
        'Gelligaer',
        'Gilfach Goch',
        'Gilwern',
        'Glan Conwy',
        'Glanaman',
        'Glandwr',
        'Glyn-Neath',
        'Glyncoch',
        'Goodwick',
        'Gorseinon',
        'Greenfield',
        'Gresford',
        'Haverfordwest',
        'Heolgerrig',
        'Holyhead',
        'Holywell',
        'Hope',
        'Caergwrle',
        'Johnston',
        'Kidwelly',
        'Knighton',
        'Lampeter',
        'Langstone',
        'Leeswood',
        'Llanberis',
        'Llanbradach',
        'Llandeilo',
        'Llandovery',
        'Llandrindod Wells',
        'Llandudno',
        'Llandudno Junction',
        'Deganwy',
        'Llandybie',
        'Llanelli',
        'Llanfairfechan',
        'Llanfairpwll',
        'Llangefni',
        'Llangollen',
        'Llangynwyd',
        'Pont-rhyd-y-cyff',
        'Llanharan',
        'Llanharry',
        'Llanhilleth',
        'Llanidloes',
        'Llanrug',
        'Llanrwst',
        'Llantrisant',
        'Pontyclun',
        'Llantwit Fardre',
        'Llantwit Major',
        'Llay',
        'Machen',
        'Machynlleth',
        'Maesteg',
        'Magor',
        'Marshfield',
        'Menai Bridge',
        'Merthyr Tydfil',
        'Merthyr Vale',
        'Milford Haven',
        'Mold',
        'Monmouth',
        'Mostyn',
        'Mountain Ash',
        'Abercynon',
        'Narberth',
        'Neath',
        'New Tredegar',
        'Newcastle Emlyn',
        'Newport',
        'Newtown',
        'Neyland',
        'Northop Hall',
        'Oakdale',
        'Pontllanfraith',
        'Ogmore Vale',
        'Pantymwyn',
        'Gwernaffield',
        'Pembroke',
        'Pembroke Dock',
        'Penarth',
        'Penclawdd',
        'Pencoed',
        'Penmaenmawr',
        'Penrhyn Bay',
        'Penrhyndeudraeth',
        'Penrhys',
        'Pentyrch',
        'Penyffordd',
        'Penygroes',
        'Pontardawe',
        'Clydach',
        'Pontarddulais',
        'Pontlliw',
        'Pontyberem',
        'Pontycymer',
        'Pontypool',
        'Pontypridd',
        'Port Talbot',
        'Porthcawl',
        'Porthmadog',
        'Prestatyn',
        'Presteigne',
        'Price Town',
        'Pwllheli',
        'Pyle',
        'Radyr',
        'Resolven',
        'Rhayader',
        'Rhondda',
        'Rhoose',
        'Rhosllanerchrugog',
        'Rhostyllen',
        'Rhuddlan',
        'Rhyl',
        'Rhymney',
        'Risca',
        'Rogiet',
        'Rosset',
        'Ruabon',
        'Ruthin',
        'Saundersfoot',
        'Seven Sisters',
        'Shotton',
        'Hawarden',
        'Soughton',
        'Southgate',
        'St Asaph',
        'St Clears',
        'St David\'s',
        'Swansea',
        'Taff\'s Well',
        'Tenby',
        'Tongwynlais',
        'Tonyrefail',
        'Tredegar',
        'Treharris',
        'Nelson',
        'Trimsaran',
        'Tumble',
        'Tywyn',
        'Underwood',
        'Usk',
        'Valley',
        'Welshpool',
        'Whelston',
        'Wrexham',
        'Y Felinheli',
        'Ynysybwl',
        'Ystradgynlais',
        'Ystalyfera'
);